# Generated by Django 4.1.7 on 2023-04-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEmetteur', models.CharField(max_length=100)),
                ('prenomEmetteur', models.CharField(max_length=100)),
                ('telephoneEmetteur', models.CharField(max_length=100)),
                ('emailEmetteur', models.CharField(max_length=200)),
                ('paysEmetteur', models.CharField(max_length=200)),
                ('departementEmetteur', models.CharField(max_length=100)),
                ('communeEmetteur', models.CharField(max_length=100)),
                ('quartierEmetteur', models.CharField(max_length=100)),
                ('detailLocalisation', models.TextField(max_length=500)),
                ('villeReception', models.CharField(max_length=200)),
                ('pointRelais', models.CharField(max_length=200)),
                ('notification', models.TextField(max_length=500)),
                ('nomDestinataire', models.CharField(max_length=200)),
                ('prenomDestinataire', models.CharField(max_length=200)),
                ('telephoneDestinataire', models.CharField(max_length=200)),
                ('emailDestinataire', models.EmailField(max_length=254)),
                ('typeColis', models.CharField(max_length=200)),
                ('poids', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('follow_code', models.CharField(max_length=200, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('transactionId', models.CharField(max_length=300, null=True, unique=True)),
                ('is_lancement', models.BooleanField(default=True)),
                ('is_enlevement', models.BooleanField(default=False)),
                ('is_acheminement', models.BooleanField(default=False)),
                ('is_reception', models.BooleanField(default=False)),
                ('is_termine', models.BooleanField(default=False)),
                ('user', models.IntegerField()),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
